//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgoSiHoa_buoi2.Contex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Status { get; set; }
        public string Hinh { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> PriceSale { get; set; }
    }
}
